server:
  type: simple
  applicationContextPath: /scigraph
  adminContextPath: /admin
  connector:
    type: http
    port: 9000

applicationContextPath: scigraph

graphConfiguration:
  location: /var/scigraph-services/graph
  indexedNodeProperties:
    - label
    - synonym
    - fragment
  exactNodeProperties:
    - label
    - synonym
  neo4jConfig:
    dump_configuration : true
    dbms.pagecache.memory : 3G

cypherResources:
    ## Get the complete CINGERI facet hierarchy
    ## #START root = node:node_auto_index(uri='http://www.w3.org/2002/07/owl#Thing')
    /dynamic/facets:
      x-query: |
              MATCH path = (facet)-[:subClassOf|equivalentClass*0..]->(root)
              WHERE facet.`http://hydro10.sdsc.edu/cinergi_ontology/cinergiExtensions.owl#cinergiFacet` = true
              AND root.`http://hydro10.sdsc.edu/cinergi_ontology/cinergiExtensions.owl#cinergiFacet` = true
              RETURN path
      get:
        operationId: allFacets
        summary: Get all facets
        description: Get all facets
        responses:
          default:
            description: success



    ## Get parent CINERGI facets for a term
    /dynamic/{term_uri}/facets:
      x-query: |
              START term = node:node_auto_index(uri={term_uri})
              MATCH path = (term)-[:subClassOf|equivalentClass*0..]->(facet)
              WHERE facet.`http://hydro10.sdsc.edu/cinergi_ontology/cinergiExtensions.owl#cinergiFacet` = true
              RETURN path
      get:
        operationId: relatedFacets
        summary: Get facets related to a term
        description: Get facets related to a term
        parameters:
          - name: term_uri
            description: The URI of the term
            required: true
            type: string
            in: query
        responses:
          default:
            description: success


